# Generated by Django 2.0.5 on 2018-05-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpref',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
