# Generated by Django 2.0.5 on 2018-05-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0003_auto_20180508_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
