# Generated by Django 2.0.5 on 2018-05-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0004_auto_20180508_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='age_range',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
